In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [4]:
X_train=pd.read_csv('Seniors.csv', usecols=['Temperature (°C)','Pressure (kPa)','Temperature x Pressure','Material Fusion Metric','Material Transformation Metric'])
Y_train=pd.read_csv('Seniors.csv', usecols=['Quality Rating'])

In [8]:
print(X_train.shape)
print(Y_train.shape)

(2500, 5)
(2500, 1)

In [5]:
X_train.head

<bound method NDFrame.head of       Temperature (°C)  Pressure (kPa)  Temperature x Pressure  \
0           209.762701        8.050855             1688.769167
1           243.037873       15.812068             3842.931469
2           220.552675        7.843130             1729.823314
3           208.976637       23.786089             4970.736918
4           184.730960       15.797812             2918.345014
...                ...             ...                     ...
2495        194.332813       22.269402             4327.675524
2496        240.467829       15.981486             3843.033197
2497        244.866196       24.901641             6097.570183
2498        138.314203       10.700640             1480.050534
2499        232.434847        6.374536             1481.664374

      Material Fusion Metric  Material Transformation Metric
0               44522.217074                    9.229576e+06
1               63020.764997                    1.435537e+07
2               49125.950249                    1.072839e+07
3               57128.881547                    9.125702e+06
4               38068.201283                    6.303792e+06
...                      ...                             ...
2495            48809.223549                    7.338530e+06
2496            61906.574136                    1.390474e+07
2497            75400.755993                    1.468142e+07
2498            20356.081611                    2.645949e+06
2499            54284.985490                    1.255747e+07

[2500 rows x 5 columns]>

In [6]:
Y_train.head

<bound method NDFrame.head of       Quality Rating
0          99.999971
1          99.985703
2          99.999758
3          99.999975
4         100.000000
...              ...
2495       99.999999
2496       99.990852
2497       99.980421
2498      100.000000
2499       99.997804

[2500 rows x 1 columns]>

In [7]:
X_train.describe()

,Temperature (°C),Pressure (kPa),Temperature x Pressure,Material Fusion Metric,Material Transformation Metric
count,2500.000000,2500.000000,2500.000000,2500.000000,2.500000e+03
mean,200.653802,14.800937,2966.560892,48385.166770,1.014740e+07
std,58.615971,5.704845,1461.402337,24053.925674,7.678297e+06
min,100.014740,5.009819,513.706875,10156.971955,9.999462e+05
25%,150.875184,9.821192,1800.528733,27504.622582,3.434285e+06
50%,200.291585,14.864597,2708.227080,44809.454736,8.034823e+06
75%,251.811806,19.722411,3929.471504,68156.553776,1.596700e+07
max,299.961716,24.999132,7365.018714,103756.181544,2.698960e+07

In [9]:
X_train['Material Transformation Metric']=np.log(X_train['Material Transformation Metric'])
X_train['Material Fusion Metric']=np.log(X_train['Material Fusion Metric'])
X_train['Temperature x Pressure']=np.log(X_train['Temperature x Pressure'])

In [10]:
X_train.describe()

,Temperature (°C),Pressure (kPa),Temperature x Pressure,Material Fusion Metric,Material Transformation Metric
count,2500.000000,2500.000000,2500.000000,2500.000000,2500.000000
mean,200.653802,14.800937,7.863160,10.644128,15.765796
std,58.615971,5.704845,0.534852,0.561123,0.934738
min,100.014740,5.009819,6.241653,9.225916,13.815457
25%,150.875184,9.821192,7.495835,10.222109,15.049319
50%,200.291585,14.864597,7.904049,10.710174,15.899295
75%,251.811806,19.722411,8.276260,11.129563,16.586035
max,299.961716,24.999132,8.904497,11.549799,17.110962

In [11]:
Y_train.describe()

       Quality Rating
count     2500.000000
mean        96.039307
std         13.306205
min          1.421653
25%         99.936589
50%         99.999996
75%        100.000000
max        100.000000

In [14]:
Y_train.corrwith(X_train)

Material Fusion Metric           NaN
Material Transformation Metric   NaN
Pressure (kPa)                   NaN
Quality Rating                   NaN
Temperature (°C)                 NaN
Temperature x Pressure           NaN
dtype: float64

In [15]:
X_train.isna().sum()

Temperature (°C)                  0
Pressure (kPa)                    0
Temperature x Pressure            0
Material Fusion Metric            0
Material Transformation Metric    0
dtype: int64

In [16]:
Y_train.isna().sum()

Quality Rating    0
dtype: int64